Cancer Biomarkers schema v2
opentargets/json_schema pull request #130
Opened 2021-08-19 07:55 UTC by ireneisdoomed

### Updates
- [X] `variantAminoacidDescriptions`, `variantFunctionalConsequenceId` have been removed from root.
- [X] `biomarker` is no longer a string at the root level. It has been renamed to `biomarkers` to be an array of structs that collects all the variant information
- [X] `biomarkers.name`: the name of the biomarker as shown in the data source. This field contains all the variants if multiple are reported. This field is common for all objects in the array.
- [X] `biomarkers.individualMutation`: when available, the precise mutation the other fields refer to is described in this field.
- [X] `biomarkers.variantId`: the genomic coordinates of the individual mutation in the CHROM_POS_REF_ALT notation
- [X] `variantFunctionalConsequenceIds`: Array with the possible functional consequences of the biomarker. As the biomarker can report multiple variants, this field can also contain multiple SO codes.
- [X] `variantId` description has been updated to establish the difference with `biomarkers.variantId`.

2021-08-19 19:05 UTC, ireneisdoomed commented
## v3 of the schema
Brand new schema again 😬
For readability, you can go to the schema tracker and compare between iter 3 (this one) and iter 2.
https://docs.google.com/spreadsheets/d/1Mowq7KsGTMtEg3wZpJBNK_UbawHKJeM9d0syT9F9AMc/edit#gid=1923708913

- [X] `biomarkers` is no longer an array of structs but a struct with two fields: `geneExpression` and `variant`.
- [X] `geneExpression` and `variant` are array of structs.
- [X] `geneExpression.id` is the Gene Ontology identifier of the change or the abscense of change in expression.
- [X] `geneExpression.label` is the label of the ID. Ideally we would want to resolve the ID in the ETL, but since I am not sure if we are able to do it, I am manually adding it for the moment.
- [X] `variant.name` when available, is the precise mutation the other fields inside `variant` refer to.
- [X] `variant.id` is the genomic coordinates of the individual mutation in the CHROM_POS_REF_ALT notation
- [X] `functionalConsequenceId` is the functional consequence of the biomarker. As the biomarker can report multiple variants, this field will be disambiguated in the parser.

2021-08-24 09:27 UTC, DSuveges requested changes

2021-08-31 08:57 UTC, ireneisdoomed commented on opentargets.json
> +              },
I had to bring this field back again to indicate the specific alteration the GO refers to as there are biomarkers with multiple ones.

2021-09-01 11:20 UTC, DSuveges commented on opentargets.json
> +                "type": "string",
Adding a comment for the `geneExpression.name` field:

```suggestion
                "type": "string",
                "description": "Raw gene expression annotation from the source",
```

2021-09-01 11:20 UTC, DSuveges approved these changes

2021-09-01 11:23 UTC, merged